Null pointers checks
linux-audit/audit-userspace pull request #361
Opened 2024-03-18 10:26 UTC by Yugend

Added some NULL pointer checks.
My static analyzer has indicated these places as dangerous, so I decided to try to fix it. I guess there's not a lot of memory allocated in these places, so these checks will probably never come in handy. But perhaps you will find them not superfluous.

2024-03-19 14:18 UTC, Yugend commented on audisp/plugins/zos-remote/zos-remote-queue.c
> +			log_err("Memory allocation error");;
Looks like there is some trouble with my code editor. I just deleted this indentation and added it again, and git showed me, that something has changed :)
Anyway, I have fixed everything you suggested, thanks!

2024-03-19 21:46 UTC, stevegrubb commented
Thanks for the patch. I'm not sure I like simple memory error messages. It doesn't give the user anything meaningful to diagnose the issue. In cases like those, it might be better to add 2  %s fields to print __FILE__ and __LINE__. This way we know where it's coming from.

2024-03-20 12:21 UTC, Yugend commented
> Thanks for the patch. I'm not sure I like simple memory error messages. It doesn't give the user anything meaningful to diagnose the issue. In cases like those, it might be better to add 2 %s fields to print **FILE** and **LINE**. This way we know where it's coming from.

Thanks for your answer!
I agree, it sounds reasonable. But I was thinking about end users, most likely not all of them may be programmers. Do you think it would be useful for them to get information about which file and which line the error occurred in?.. Perhaps something like "you need more RAM" would be more useful for end users?

For the same reason I replaced 'assert' macros, which only work in debug version of project.

2024-03-20 12:54 UTC, stevegrubb commented
I try to keep the memory footprint of auditd low. It uses the stack in many places to avoid unnecessary allocations while processing events. They are not likely to need more memory. If we hit a NULL allocation, it's more likely because memory is leaking somewhere or we have memory fragmentation. Providing the file and line gives them something to report that someone can look into.

2024-03-22 11:40 UTC, Yugend commented
> Providing the file and line gives them something to report that someone can look into.

Then it really makes sense, I didn't think about it.
Added two commits to my pull request. I took into account your recommendations about error messages and tried to fix #362 opened by myself.

2024-03-26 08:00 UTC, Cropi requested changes

2024-03-26 08:00 UTC, Cropi commented on src/auditctl.c
> +			return 1;
I would suggest to close the file descriptor before leaving the function, via `fclose(f);`

2024-03-27 14:45 UTC, Yugend commented
Thank you for your advices, guys, I really appreciate it. I am not a very experienced coder, including in git. I'm sorry to give you so much trouble with my PR.

2024-04-09 21:55 UTC, stevegrubb commented
Hello, I was looking to apply this patch, but it has 2 problems. It patches ipctab.h and auditd.c which were changed on the master branch while this patch was being made. I don't know how it got added to the patch, but we need to drop that portion of the patch. Revert the changes to those 2 files. Or if you allow editing of the PR by the maintainers, I might be able to fix it.

2024-04-10 19:17 UTC, stevegrubb commented
It was applied as a series of commits. The last of which is commit 3f3b3a2. Thanks for the patch!

2024-04-10 19:17 UTC, closed without merging

2024-04-12 14:24 UTC, Yugend commented
Maybe it's my fault, I clicked somewhere wrong when I saw a message about differences in the master branch and my PR or something like that.
Anyway, thank you for the feedback!